# -*- coding: utf-8 -*-
"""exercícios 13/03

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1X1O3hV2YAjFAcuJvLhnn_jga4z3IfcyH
"""

print('Contagem de palavras')
frase = str(input('Digite uma frase: ')).split()
print(f'Quantidade de palavras: {len(frase)}')

print('Maior número da lista')
n = list()
maior = quant = 0
for i in range(1, 5):
  n.append(int(input(f'{i}° número: ')))
  quant += 1
    if n > maior:
        maior = n

print(f'Lista de números {n}')
print(f'O maior é {maior}')

print('Contagem de números PARES')
num = [12, 7, 9, 20, 33, 18, 4]
par = 0
for c in num:
  if c % 2 == 0:
    par += 1
print(f'Há {par} números pares.')

print('Filtrando dados')
idades = [15, 18, 22, 17, 30, 14, 40]
maior = 0
for i in idades:
  if i >= 18:
    maior += 1
print(f'Os maiores de idade são {maior}')

print('Frequência de números')
dados = [1, 2, 2, 3, 3, 3, 4, 4, 5]
for c in dados: