# -*- coding: utf-8 -*-
"""Exercicios_regressao_entregas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SMbwZVCYMfWNL3nFlwYLCKj1nim-cv8q

# Lista de Exercícios – Regressão Linear com Base de Logística

## Problema: prever tempo de entrega

Neste notebook, vamos trabalhar com uma base simulada de uma empresa de entregas.

A empresa quer prever o **tempo de entrega em minutos** com base em características do pedido e da entrega.

## Objetivo geral

Criar modelos de regressão linear para prever:

> quanto tempo uma entrega deve demorar.

Essa é uma aplicação mais próxima de problemas reais de empresas, e-commerce, logística e sistemas de roteirização.

# Contexto da base

Cada linha representa um pedido entregue.

## Colunas

| Coluna | Descrição |
|---|---|
| id_pedido | Identificador do pedido |
| distancia_km | Distância entre loja/centro de distribuição e cliente |
| peso_kg | Peso total do pedido |
| qtd_itens | Quantidade de itens no pedido |
| valor_pedido | Valor total do pedido |
| trafego | Condição do tráfego: baixo, medio ou alto |
| clima | Condição climática: normal, chuva ou forte_chuva |
| tipo_entrega | normal ou expressa |
| regiao | centro, bairro ou zona_rural |
| tempo_entrega_min | Tempo de entrega em minutos |
| atrasou | Indica se a entrega passou de 120 minutos |

## Variável alvo para regressão

A variável que queremos prever é:

`tempo_entrega_min`

# Importação das bibliotecas
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from sklearn.model_selection import train_test_split

df = pd.read_csv('base_logistica_entregas.csv')
df

"""# Criando a base de dados

# Parte A – Exploração inicial da base

## Exercício 1
Mostre as 10 primeiras linhas da base.

## Exercício 2
Mostre as 10 últimas linhas da base.

## Exercício 3
Use `.info()` para verificar os tipos de dados.

## Exercício 4
Use `.describe()` para analisar as variáveis numéricas.

## Exercício 5
Verifique se há valores nulos.

## Exercício 6
Quantas linhas e colunas existem?

## Exercício 7
Qual é a variável alvo do problema de regressão?

## Exercício 8
Quais variáveis parecem ser boas candidatas para prever tempo de entrega?

## Exercício 9
Quais variáveis são categóricas?

## Exercício 10
Por que não podemos usar variáveis categóricas diretamente na regressão linear sem tratamento?
"""

# Espaço para resolver a Parte A
df.head(10)

df.tail(10)

df.info()

df.describe()

df.isnull()

df.shape

'''
7 - tempo_entrega_min

8 - Distância, clima e região

9 - tráfego, clima, tipo_entrega, região e atraso

10 - Porque regressão trabalha com números, faz operações matemáticas.
'''

tempo_medio = df['tempo_entrega_min'].mean()
print(tempo_medio)

mediana = df['tempo_entrega_min'].median()
mediana

desvio_padao = df['tempo_entrega_min'].std()
desvio_padao

tempo_minimo = df['tempo_entrega_min'].min()
tempo_maximo = df['tempo_entrega_min'].max()
print(f'O tempo mínimo é {tempo_minimo}. E o máximo {tempo_maximo}')

q1 = df['tempo_entrega_min'].quantile(0.25)
q3 = df['tempo_entrega_min'].quantile(0.75)

print(f'Primeiro Quartil (Q1): {q1} minutos')
print(f'Segundo Quartil (Q2 - Mediana): {mediana} minutos')
print(f'Terceiro Quartil (Q3): {q3} minutos')

'''
17 -
  Média é a soma de todos os valores
  Mediana é o valor que no meio dos dados

18 - Sim, o desvio padrão está um pouco em relação a média

19 - Sim. Com base no quartil, mostra que pode haver algum outlier
'''

tempo_medio_por_tipo = df.groupby('tipo_entrega')['tempo_entrega_min'].mean().reset_index()
display(tempo_medio_por_tipo)

tempo_medio_por_trafego = df.groupby('trafego')['tempo_entrega_min'].mean().reset_index()
tempo_medio_por_trafego

"""# Parte B – Estatística descritiva

## Exercício 11
Calcule a média do tempo de entrega.

## Exercício 12
Calcule a mediana do tempo de entrega.

## Exercício 13
Calcule o desvio padrão do tempo de entrega.

## Exercício 14
Calcule o tempo mínimo e máximo de entrega.

## Exercício 15
Calcule os quartis de `tempo_entrega_min`.

## Exercício 16
Interprete a diferença entre média e mediana.

## Exercício 17
Existe muita variação nos tempos de entrega? Use o desvio padrão para justificar.

## Exercício 18
Existe algum possível outlier no tempo de entrega?

## Exercício 19
Compare o tempo médio de entrega por tipo de entrega.

## Exercício 20
Compare o tempo médio de entrega por condição de tráfego.

# Parte C – Visualização

## Exercício 21
Faça um histograma de `tempo_entrega_min`.

## Exercício 22
Faça um boxplot de `tempo_entrega_min`.

## Exercício 23
Faça um gráfico de dispersão entre `distancia_km` e `tempo_entrega_min`.

## Exercício 24
Faça um gráfico de dispersão entre `peso_kg` e `tempo_entrega_min`.

## Exercício 25
Faça um gráfico de dispersão entre `qtd_itens` e `tempo_entrega_min`.

## Exercício 26
Faça um boxplot de tempo de entrega por `trafego`.

## Exercício 27
Faça um boxplot de tempo de entrega por `clima`.

## Exercício 28
Faça um boxplot de tempo de entrega por `tipo_entrega`.

## Exercício 29
Visualmente, qual variável parece mais relacionada ao tempo de entrega?

## Exercício 30
O gráfico sugere relação linear entre distância e tempo?
"""

plt.figure(figsize=(10, 6))
sns.histplot(df['tempo_entrega_min'], kde=True, bins=20)
plt.title('Distribuição do Tempo de Entrega em Minutos')
plt.xlabel('Tempo de Entrega (minutos)')
plt.ylabel('Frequência')
plt.grid(axis='y', alpha=0.75)
plt.show()

plt.figure(figsize=(8, 6))
sns.boxplot(x=df['tempo_entrega_min'])
plt.title('Boxplot do Tempo de Entrega em Minutos')
plt.xlabel('Tempo de Entrega (minutos)')
plt.grid(axis='x', alpha=0.75)
plt.show()

plt.figure(figsize=(10, 6))
sns.scatterplot(x='distancia_km', y='tempo_entrega_min', data=df)
plt.title('Dispersão entre Distância e Tempo de Entrega')
plt.xlabel('Distância (km)')
plt.ylabel('Tempo de Entrega (minutos)')
plt.grid(True, linestyle='--', alpha=0.7)
plt.show()

plt.figure(figsize=(10, 6))
sns.scatterplot(x='peso_kg', y='tempo_entrega_min', data=df)
plt.title('Dispersão entre Peso e Tempo de Entrega')
plt.xlabel('Peso (kg)')
plt.ylabel('Tempo de Entrega (minutos)')
plt.grid(True, linestyle='--', alpha=0.7)
plt.show()

plt.figure(figsize=(10, 6))
sns.scatterplot(x='qtd_itens', y='tempo_entrega_min', data=df)
plt.title('Dispersão entre Quantidade de Itens e Tempo de Entrega')
plt.xlabel('Quantidade de Itens')
plt.ylabel('Tempo de Entrega (minutos)')
plt.grid(True, linestyle='--', alpha=0.7)
plt.show()

plt.figure(figsize=(10, 6))
sns.boxplot(x='trafego', y='tempo_entrega_min', data=df, palette='viridis')
plt.title('Boxplot do Tempo de Entrega por Tráfego')
plt.xlabel('Condição de Tráfego')
plt.ylabel('Tempo de Entrega (minutos)')
plt.grid(axis='y', alpha=0.75)
plt.show()

plt.figure(figsize=(10, 6))
sns.boxplot(x='clima', y='tempo_entrega_min', data=df, palette='plasma')
plt.title('Boxplot do Tempo de Entrega por Clima')
plt.xlabel('Condição Climática')
plt.ylabel('Tempo de Entrega (minutos)')
plt.grid(axis='y', alpha=0.75)
plt.show()

plt.figure(figsize=(10, 6))
sns.boxplot(x='tipo_entrega', y='tempo_entrega_min', data=df, palette='viridis')
plt.title('Boxplot do Tempo de Entrega por Tipo de Entrega')
plt.xlabel('Tipo de Entrega')
plt.ylabel('Tempo de Entrega (minutos)')
plt.grid(axis='y', alpha=0.75)
plt.show()

'''
35 - Distância. Quanto maior a distância, maior o tempo de entrega.

36 - Não. Uma alta correlação não prova causalidade. Indica que elas andam juntas

37 - Não exatamente. Pode ser importante combinada com outras variáveis.

38 - Sim. Ela é que vai dizer o tempo de médio de entrega.

39 - Aparentemente não tanto. Mas, há uma pequena relevância sem muita influência

40 - De início escolheria distância e tempo de entrega
'''

"""# Parte D – Correlação

Para calcular correlação, use apenas variáveis numéricas.

## Exercício 31
Crie um DataFrame apenas com variáveis numéricas.

## Exercício 32
Calcule a matriz de correlação.

## Exercício 33
Faça um heatmap da matriz de correlação.

## Exercício 34
Qual variável numérica tem maior correlação positiva com `tempo_entrega_min`?

## Exercício 35
Qual variável numérica parece ter menor relação com `tempo_entrega_min`?

## Exercício 36
Correlação alta prova causalidade? Explique.

## Exercício 37
Se `valor_pedido` tiver baixa correlação com tempo, isso significa que nunca deve ser usado? Explique.

## Exercício 38
A variável `distancia_km` parece importante? Justifique.

## Exercício 39
A variável `peso_kg` parece importante? Justifique.

## Exercício 40
Quais variáveis você escolheria para um primeiro modelo simples?
"""

# Espaço para resolver a Parte D

df_numerico = df.select_dtypes(include=np.number)
display(df_numerico.head())

matriz_correlacao = df_numerico.corr()
display(matriz_correlacao)

plt.figure(figsize=(10, 8))
sns.heatmap(matriz_correlacao, annot=True, cmap='coolwarm', fmt=".2f")
plt.title('Mapa de Calor da Matriz de Correlação')
plt.show()

'''
34 - É a distância. Quanto maior a distância, maior o tempo de entrega.

35 - Valor do pedido

36 - Não. Uma alta correlação não prova causalidade. Indica que elas andam juntas

37 - Não exatamente. Pode ser importante combinada com outras variáveis.

38 - Sim. Ela é que vai dizer o tempo de médio de entrega.

39 - Aparentemente não tanto. Mas, há uma pequena relevância sem muita influência

40 - De início escolheria distância e tempo de entrega
'''

"""# Parte E – Regressão linear simples

Vamos começar com um modelo simples:

`distancia_km` → `tempo_entrega_min`

## Exercício 41
Crie `X` com a coluna `distancia_km`.

## Exercício 42
Crie `y` com `tempo_entrega_min`.

## Exercício 43
Treine um modelo de regressão linear.

## Exercício 44
Mostre o coeficiente angular.

## Exercício 45
Mostre o intercepto.

## Exercício 46
Interprete o coeficiente angular.

## Exercício 47
Faça previsões para todos os pedidos.

## Exercício 48
Crie uma tabela com tempo real, tempo previsto e erro.

## Exercício 49
Calcule MAE, RMSE e R².

## Exercício 50
Interprete as métricas.
"""

x = df['distancia_km']
y = df['tempo_entrega_min']

X = x.values.reshape(-1, 1)

modelo = LinearRegression()
modelo.fit(X, y)

print(f"Coeficiente Angular (slope): {modelo.coef_[0]:.2f}")

print(f"Intercept: {modelo.intercept_:.2f}")

'''
46 - Mostra que a cada KM a um aumento adicional de  1.75 minutos
'''

previsoes = modelo.predict(X)

resultados = pd.DataFrame({
    'id_pedido': df['id_pedido'],
    'tempo_real': y,
    'tempo_previsto': previsoes.flatten(),
    'erro': y - previsoes.flatten()
})

display(resultados.head())

mae = mean_absolute_error(y, previsoes)
mse = mean_squared_error(y, previsoes)
rmse = np.sqrt(mse)
r2 = r2_score(y, previsoes)

print(f"Mean Absolute Error (MAE): {mae:.2f}")
print(f"Root Mean Squared Error (RMSE): {rmse:.2f}")
print(f"R-squared (R²): {r2:.2f}")

'''
MAE - siginica que, em média, as previsões estão erradas em 26 minutos

RMSE - Métrica que penaliza erros maiores, principalmente erros mais extremos.

R² - 55% de variação do tempo pode ser explicado pela distância percorrida

'''

"""# Parte F – Visualizando a reta do modelo simples

## Exercício 51
Faça um gráfico de dispersão entre distância e tempo real.

## Exercício 52
Adicione a reta de regressão no gráfico.

## Exercício 53
O modelo parece representar bem os dados?

## Exercício 54
Existem pontos muito distantes da reta?

## Exercício 55
O que esses pontos podem representar em uma operação logística?
"""

plt.figure(figsize=(10, 6))
sns.scatterplot(x='distancia_km', y='tempo_entrega_min', data=df, label='Dados Reais')
plt.title('Dispersão entre Distância e Tempo Real de Entrega com Reta de Regressão')
plt.xlabel('Distância (km)')
plt.ylabel('Tempo Real de Entrega (minutos)')
plt.grid(True, linestyle='--', alpha=0.7)
plt.legend()
plt.show()

plt.figure(figsize=(10, 6))
sns.scatterplot(x='distancia_km', y='tempo_entrega_min', data=df, label='Dados Reais')
plt.plot(X, previsoes, color='red', label='Reta de Regressão')
plt.title('Dispersão entre Distância e Tempo Real de Entrega com Reta de Regressão')
plt.xlabel('Distância (km)')
plt.ylabel('Tempo Real de Entrega (minutos)')
plt.grid(True, linestyle='--', alpha=0.7)
plt.legend()
plt.show()

'''
Representa moderadamente. Há muitos pontos distante da reta.
'''

"""# Parte G – Fazendo previsões reais

Use o modelo simples com distância.

## Exercício 56
Preveja o tempo de entrega para uma entrega de 5 km.

## Exercício 57
Preveja o tempo de entrega para uma entrega de 20 km.

## Exercício 58
Preveja o tempo de entrega para uma entrega de 60 km.

## Exercício 59
As previsões fazem sentido?

## Exercício 60
Quais informações importantes o modelo simples está ignorando?
"""

# Espaço para resolver a Parte G

distancia_5km = np.array([[5]])
previsao_5km = modelo.predict(distancia_5km)
print(f"Previsão para 5 km: {previsao_5km[0]:.2f} minutos")

distancia_20km = np.array([[20]])
previsao_20km = modelo.predict(distancia_20km)
print(f'Previsão para 20km: {previsao_20km[0]:.2f}')

distancia_60km = np.array([[60]])
previsao_60km = modelo.predict(distancia_60km)
print(f'Previsão para 60Km: {previsao_60km[0]:.2f}')

'''
59 - Sim. De acorda com a distância o tempo de entrega aumenta.

60 - Clima, peso, trâfego e clima, que são os outros 45% de variação. O que acaba influenciando no tempo de entrega.
'''

"""# Parte H – Tratamento de variáveis categóricas

Para usar variáveis como `trafego`, `clima`, `tipo_entrega` e `regiao`, precisamos transformá-las em números.

Uma forma comum é usar `pd.get_dummies()`.

## Exercício 61
Crie uma versão da base com variáveis categóricas transformadas em dummies.

## Exercício 62
Mostre as primeiras linhas da base transformada.

## Exercício 63
Explique o que o `get_dummies()` fez.

## Exercício 64
Por que usamos `drop_first=True`?

## Exercício 65
Quais novas colunas foram criadas?
"""

# Exemplo inicial para a Parte H

df_modelo = pd.get_dummies(
    df,
    columns=["trafego", "clima", "tipo_entrega", "regiao"],
    drop_first=True
)

df_modelo.head()

df_modelo = pd.get_dummies(
    df,
    columns=["trafego", "clima", "tipo_entrega", "regiao"],
    drop_first=True
)

df_modelo.head()

'''
63 - Converteu as variáveis categóricas em um formato númerico para cada coluna.

64 - Remove colunas redundantes, garantindo modelo mais estável.

65 - trafego baixo e médio, clima normal e chuva forte, região centro.

'''

"""# Parte I – Regressão linear múltipla

Agora vamos usar várias variáveis ao mesmo tempo.

## Exercício 66
Crie `X` com todas as variáveis explicativas numéricas e dummies.

Não inclua:
- `id_pedido`
- `tempo_entrega_min`
- `atrasou`

## Exercício 67
Crie `y` com `tempo_entrega_min`.

## Exercício 68
Treine um modelo de regressão linear múltipla.

## Exercício 69
Faça previsões.

## Exercício 70
Calcule MAE.

## Exercício 71
Calcule RMSE.

## Exercício 72
Calcule R².

## Exercício 73
Compare com o modelo simples.

## Exercício 74
O modelo múltiplo melhorou?

## Exercício 75
Quais variáveis parecem mais importantes?
"""

# Espaço para resolver a Parte I

colunas_para_X = [col for col in df_modelo.columns if col not in ['id_pedido', 'tempo_entrega_min', 'atrasou']]
X_multi = df_modelo[colunas_para_X]
y_multi = df_modelo['tempo_entrega_min']

print("Primeiras 5 linhas de X:")
display(X_multi.head())

modelo_multi = LinearRegression()
modelo_multi.fit(X_multi, y_multi)

previsoes_multi = modelo_multi.predict(X_multi)

mae_multi = mean_absolute_error(y_multi, previsoes_multi)
print(f"Mean Absolute Error (MAE) para o modelo múltiplo: {mae_multi:.2f}")

mse_multi = mean_squared_error(y_multi, previsoes_multi)
rmse_multi = np.sqrt(mse_multi)
print(f"Root Mean Squared Error (RMSE) para o modelo múltiplo: {rmse_multi:.2f}")

r2_multi = r2_score(y_multi, previsoes_multi)
print(f"R-squared (R²) para o modelo múltiplo: {r2_multi:.2f}")

'''
73 -
  O modelo de regressão linear múltipla demonstrou um desempenho significativamente melhor do que o modelo simples.
  Com um R² de 0.87, ele explica 87% da variação no tempo de entrega, e seus erros médios
  (MAE: 14.48 min, RMSE: 17.58 min) são consideravelmente menores que os do modelo
  simples (R²: 0.55, MAE: 26.28 min, RMSE: 33.01 min).

74 -
  Sim, o modelo múltiplo apresentou uma melhoria significativa em comparação com o modelo simples.
  O R² aumentou de 0.55 para 0.87, o que significa que o modelo múltiplo explica 87% da variação no
  tempo de entrega, enquanto o modelo simples explicava apenas 55%. Além disso, o MAE e RMSE são
  consideravelmente menores no modelo múltiplo, indicando previsões mais precisas.

75 - Distãncia, Região,


'''

coeficientes = pd.DataFrame({
    'Variavel': X_multi.columns,
    'Coeficiente': modelo_multi.coef_
})

# Adicionar o intercepto para uma visão completa
intercepto_df = pd.DataFrame([{'Variavel': 'Intercepto', 'Coeficiente': modelo_multi.intercept_}])
coeficientes = pd.concat([coeficientes, intercepto_df], ignore_index=True)

# Ordenar por valor absoluto do coeficiente para ver as mais influentes
coeficientes['abs_coeficiente'] = np.abs(coeficientes['Coeficiente'])
coeficientes = coeficientes.sort_values(by='abs_coeficiente', ascending=False).drop(columns='abs_coeficiente')

display(coeficientes)

"""# Parte J – Coeficientes do modelo múltiplo

## Exercício 76
Crie uma tabela com variáveis e coeficientes.

## Exercício 77
Ordene os coeficientes do maior para o menor.

## Exercício 78
Quais coeficientes aumentam o tempo previsto?

## Exercício 79
Quais coeficientes diminuem o tempo previsto?

## Exercício 80
Interprete o coeficiente de `distancia_km`.

## Exercício 81
Interprete o coeficiente de `tipo_entrega_expressa`.

## Exercício 82
Interprete o coeficiente de `trafego_alto`.

## Exercício 83
Interprete o coeficiente de `clima_forte_chuva`.

## Exercício 84
Os sinais dos coeficientes fazem sentido?

## Exercício 85
O que poderia indicar um coeficiente estranho?
"""

coeficientes = pd.DataFrame({
    'Variavel': X_multi.columns,
    'Coeficiente': modelo_multi.coef_
})

# Adicionar o intercepto para uma visão completa
intercepto_df = pd.DataFrame([{'Variavel': 'Intercepto', 'Coeficiente': modelo_multi.intercept_}])
coeficientes = pd.concat([coeficientes, intercepto_df], ignore_index=True)

# Ordenar por valor absoluto do coeficiente para ver as mais influentes
coeficientes['abs_coeficiente'] = np.abs(coeficientes['Coeficiente'])
coeficientes = coeficientes.sort_values(by='abs_coeficiente', ascending=False).drop(columns='abs_coeficiente')

display(coeficientes)

coeficientes_ordenados_maior_menor = coeficientes.sort_values(by='Coeficiente', ascending=False)
display(coeficientes_ordenados_maior_menor)

'''
78 -
  Os coeficientes que aumentam o tempo de entrega previsto são:

  Intercepto: 58.86 (valor base quando todas as outras variáveis são zero)
  clima_forte_chuva: 28.84
  tipo_entrega_normal: 25.28
  regiao_zona_rural: 14.67
  qtd_itens: 2.56
  distancia_km: 1.80
  peso_kg: 1.44
  valor_pedido: 0.00015


79 -
  Os coeficientes que diminuem o tempo previsto (possuem valor negativo) são:

  trafego_baixo: -35.00
  clima_normal: -12.48
  regiao_centro: -11.64
  trafego_medio: -17.82

80 - mantendo todas as outras variáveis constantes, o coeficiente de distância
para cada 1km adicional na distância.

81 - Como a coluna tipo_entrega_normal representa um pedido de entrega 'normal',
mantendo todas as outras variáveis constantes, uma
entrega normal leva cerca de 25.28 minutos a mais do que uma entrega expressa.

82 - o tráfego baixo reduz o tempo de entrega em 35 minutos e o tráfego
médio reduz o tempo de entrega em 17.82 minutos, mantendo o restante constante.

83 - O coeficiente de clima_forte_chuva é 28.84. Isso significa que, em condições de chuva forte,
o tempo de entrega aumenta em aproximadamente 28.84 minutos em
comparação com dias de chuva (clima 'chuva'), mantendo todas as outras variáveis constantes.

84 - Sim, os sinais fazem sentido: variáveis como distância, peso, quantidade de itens, chuva forte e entrega
 normal aumentam o tempo (coeficientes positivos). Já o tráfego baixo/médio, clima normal e região central
 diminuem o tempo (coeficientes negativos), o que é lógico para um tempo de entrega.


85 - Um coeficiente estranho geralmente indica problemas com os dados ou com o modelo, como:
Variáveis muito parecidas (multicolinearidade): Coeficientes ficam instáveis.
Valores muito diferentes (outliers): Distorcem os resultados.
Modelo incompleto ou incorreto: Faltam variáveis importantes ou a relação não é linear.
'''

"""# Parte K – Treino e teste

## Exercício 86
Separe os dados em treino e teste com `test_size=0.3` e `random_state=42`.

## Exercício 87
Treine o modelo nos dados de treino.

## Exercício 88
Faça previsões nos dados de teste.

## Exercício 89
Calcule MAE no teste.

## Exercício 90
Calcule RMSE no teste.

## Exercício 91
Calcule R² no teste.

## Exercício 92
Compare com as métricas do treino.

## Exercício 93
O modelo parece generalizar bem?

## Exercício 94
O que indicaria overfitting?

## Exercício 95
Quais cuidados você teria antes de colocar esse modelo em produção?
"""

# Espaço para resolver a Parte K

X_train, X_test, y_train, y_test = train_test_split(X_multi, y_multi, test_size=0.3, random_state=42)

print(f'Tamanho do conjunto de treino (X_train): {X_train.shape}')
print(f'Tamanho do conjunto de teste (X_test): {X_test.shape}')
print(f'Tamanho do conjunto de treino (y_train): {y_train.shape}')
print(f'Tamanho do conjunto de teste (y_test): {y_test.shape}')

modelo_multi.fit(X_train, y_train)

previsoes_teste = modelo_multi.predict(X_test)
print("Primeiras 5 previsões no conjunto de teste:")
print(previsoes_teste[:5])

mae_teste = mean_absolute_error(y_test, previsoes_teste)
print(f"Mean Absolute Error (MAE) no conjunto de teste: {mae_teste:.2f}")

mse_teste = mean_squared_error(y_test, previsoes_teste)
rmse_teste = np.sqrt(mse_teste)
print(f"Root Mean Squared Error (RMSE) no conjunto de teste: {rmse_teste:.2f}")

r2_teste = r2_score(y_test, previsoes_teste)
print(f"R-squared (R²) no conjunto de teste: {r2_teste:.2f}")

previsoes_treino = modelo_multi.predict(X_train)

mae_treino = mean_absolute_error(y_train, previsoes_treino)
mse_treino = mean_squared_error(y_train, previsoes_treino)
rmse_treino = np.sqrt(mse_treino)
r2_treino = r2_score(y_train, previsoes_treino)

print(f"\n--- Métricas do Treino ---")
print(f"MAE no Treino: {mae_treino:.2f}")
print(f"RMSE no Treino: {rmse_treino:.2f}")
print(f"R-squared (R²) no Treino: {r2_treino:.2f}")

print(f"\n--- Métricas do Teste ---")
print(f"MAE no Teste: {mae_teste:.2f}")
print(f"RMSE no Teste: {rmse_teste:.2f}")
print(f"R-squared (R²) no Teste: {r2_teste:.2f}")

print(f"\n--- Comparação ---")
print(f"A diferença entre MAE (Treino - Teste) é: {mae_treino - mae_teste:.2f}")
print(f"A diferença entre RMSE (Treino - Teste) é: {rmse_treino - rmse_teste:.2f}")
print(f"A diferença entre R² (Treino - Teste) é: {r2_treino - r2_teste:.2f}")

'''
Carregamos os dados de entrega e realizamos uma exploração inicial. Em seguida, construímos dois modelos de regressão linear
para prever o tempo de entrega: um simples, usando apenas distancia_kmvariáveis ​​categóricas, e outro mais complexo, usando
múltiplas variáveis, incluindo variáveis ​​categóricas transformadas. O modelo de regressão múltipla apresentou desempenho
significativamente superior ao modelo simples. Dividimos os dados em conjuntos de treinamento e teste, treinamos o melhor modelo e
avaliamos seu desempenho, confirmando que ele generaliza bem para novos dados.

94 - O sobreajuste (overfitting) é indicado se o modelo apresentar um desempenho significativamente melhor nos dados de treinamento
do que nos dados de teste.

95 - Carregamos e exploramos os dados de entrega. Construímos e comparamos dois modelos de regressão linear para prever o tempo de
entrega: um simples (apenas distância) e um múltiplo (com mais variáveis). O modelo múltiplo demonstrou ser superior.
Separamos os dados para treino e teste, e o modelo mostrou boa capacidade de generalização.
'''

"""# Parte L – Desafio final: relatório para a empresa

A empresa quer saber se é possível prever o tempo de entrega antes do pedido sair para rota.

## Exercício 96
Treine o melhor modelo que conseguir.

## Exercício 97
Crie uma tabela com:
- tempo real
- tempo previsto
- erro
- erro absoluto

## Exercício 98
Mostre os 10 pedidos com maior erro absoluto.

## Exercício 99
Analise possíveis motivos para os maiores erros.

## Exercício 100
Escreva uma conclusão para a empresa respondendo:

1. O modelo é útil?
2. Qual o erro médio em minutos?
3. Quais variáveis mais influenciam o tempo?
4. O modelo deve ser usado sozinho para tomar decisões?
5. Que melhorias poderiam ser feitas com mais dados?
"""

# Treine o melhor modelo (regressão linear múltipla) no dataset completo
modelo_final = LinearRegression()
modelo_final.fit(X_multi, y_multi)

print("Modelo final treinado com sucesso!")

previsoes_finais = modelo_final.predict(X_multi)

tabela_resultados = pd.DataFrame({
    'id_pedido': df_modelo['id_pedido'],
    'tempo_real': y_multi,
    'tempo_previsto': previsoes_finais,
    'erro': y_multi - previsoes_finais,
    'erro_absoluto': np.abs(y_multi - previsoes_finais)
})

display(tabela_resultados.head())

pedidos_maior_erro = tabela_resultados.sort_values(by='erro_absoluto', ascending=False)
display(pedidos_maior_erro.head(10))

'''
99 -
  O notebook explorou a previsão do tempo de entrega. Iniciamos com uma análise de dados, visualizações e correlações.
  Depois, construímos e comparamos dois modelos de regressão linear:

  Modelo Simples (Distância): Previu o tempo de entrega com R² de 0.55.
  Modelo Múltiplo (Distância + Variáveis Categóricas): Teve um desempenho muito melhor, com R² de 0.87.
  Variáveis como distância, tráfego, clima, tipo de entrega e região foram as mais influentes.


'''

'''
1 -
  O modelo é útil? Sim, o modelo é útil. Ele explica 83% da variação no tempo de entrega
  (R² de 0.83 no conjunto de teste), o que é um bom indicador para a previsão.

2- Qual o erro médio em minutos? O erro médio absoluto é de aproximadamente 16.38 minutos (MAE no conjunto de teste).

3 - Quais variáveis mais influenciam o tempo? As variáveis que mais influenciam são: distância,
 condições de tráfego, condições climáticas, o tipo de entrega (normal/expressa) e a região da entrega.

4 -
  O modelo deve ser usado sozinho para tomar decisões? Não. Embora seja um bom ponto de partida, o
  modelo não deve ser usado sozinho para decisões críticas. Fatores não incluídos (como horário de pico,
  problemas na rota, indisponibilidade) podem gerar erros. Ele é uma ferramenta de apoio.

5 -

  Que melhorias poderiam ser feitas com mais dados? Com mais dados, poderíamos explorar:
   - Variáveis adicionais: Dados sobre o horário do dia, dia da semana/mês, eventos locais (feriados, shows).
   - Dados mais granulares: Tipos específicos de clima (neblina, geada), nível de congestionamento exato.
   - Histórico de motoristas/rotas: Desempenho de motoristas ou rotas específicas.
   - Modelos mais avançados: Abordagens não-lineares ou modelos de séries temporais se o volume de dados permitir.
'''

"""# Função auxiliar para avaliação de modelos

Use depois de tentar resolver manualmente.
"""

def avaliar_regressao(nome, y_real, y_pred):
    mae = mean_absolute_error(y_real, y_pred)
    mse = mean_squared_error(y_real, y_pred)
    rmse = np.sqrt(mse)
    r2 = r2_score(y_real, y_pred)

    return {
        "modelo": nome,
        "MAE": mae,
        "MSE": mse,
        "RMSE": rmse,
        "R2": r2
    }

"""# Fechamento

Com esta lista, você praticou um fluxo mais próximo de um problema real:

- exploração de dados;
- visualização;
- correlação;
- transformação de variáveis categóricas;
- regressão linear simples;
- regressão linear múltipla;
- treino e teste;
- avaliação de modelo;
- interpretação para tomada de decisão.
"""