# -*- coding: utf-8 -*-
"""notebook_exercicios_pandas_numpy.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17gIBPn-0mWQSEr9-VeH1MWdf4-DCwVr2

# Exercícios de revisão — Upload de arquivo, Pandas e NumPy

Nesta atividade, você vai usar a planilha **`base_exercicios_alunos_pandas.xlsx`** para praticar leitura de arquivo, exploração de dados, filtros, tratamento simples e uma introdução ao **NumPy**.

> Professor: você pode pedir que os alunos resolvam primeiro sozinhos e depois fazer a correção em sala.

## 1. Importando as bibliotecas

Use esta célula para importar as bibliotecas necessárias.
"""

import pandas as pd
import numpy as np

"""## 2. Carregando o arquivo

Se estiver no **Google Colab**, primeiro envie a planilha.

Se estiver no **Jupyter Notebook**, basta garantir que o arquivo está na mesma pasta do notebook.

"""

from google.colab import files
uploaded = files.upload()
import pandas as pd

df = pd.read_excel("base_exercicios_alunos_pandas.xlsx")
df.head()

"""## 3. Conhecendo a base

### Exercício 1
Mostre as **5 primeiras linhas** da base.

### Exercício 2
Mostre as **5 últimas linhas** da base.

### Exercício 3
Descubra:
- quantidade de linhas e colunas
- nomes das colunas
- tipos de dados

"""

df.head()

df.tail()

df.info()

df.columns

df.dtypes

"""## 4. Seleção de colunas

### Exercício 4
Mostre apenas as colunas:
- `nome`
- `curso`
- `turma`
- `nota1`

### Exercício 5
Crie um novo DataFrame chamado `df_notas` contendo:
- `nome`
- `nota1`
- `nota2`
- `faltas`

"""

df[['nome', 'curso', 'turma', 'nota1']]

df_notas = df[['nome', 'nota1', 'nota2', 'faltas']].copy()

df_notas

"""## 5. Filtros

### Exercício 6
Filtre apenas os alunos do curso **IA**.

### Exercício 7
Filtre apenas os alunos com `nota1` maior ou igual a **7**.

### Exercício 8
Filtre apenas os alunos da turma **B** e do curso **Dados**.

### Exercício 9
Filtre os alunos com mais de **5 faltas**.

"""

df[df['curso']=='IA']

df[df['nota1'] >= 7]

dados = df[(df['turma']=='B') & (df['curso'] == 'Dados')]
dados

df.head()

df[df['faltas'] >= 5]

df

"""## 6. Valores nulos

### Exercício 10
Verifique quantos valores nulos existem em cada coluna.

### Exercício 11
Mostre apenas as linhas onde a coluna `idade` está nula.

### Exercício 12
Preencha os valores nulos de `nota1` com a média da coluna `nota1`.

"""

df.isnull().sum()

df[df['idade'].isnull()]

media_1 = df['nota1'].median()
df['nota1'] = df['nota1'].fillna(round(media_1, 1))
df['nota1']

"""## 7. Tratamento de texto e padronização

### Exercício 13
Padronize a coluna `bolsista` para ficar apenas com:
- `Sim`
- `Não`

Dica: existem valores como `SIM`, `sim`, `Nao`.

### Exercício 14
Padronize a coluna `uf` para letras maiúsculas.

### Exercício 15
Padronize a coluna `cidade` no formato título.
Exemplo:
- `brasília` → `Brasília`

"""

df['bolsista'] = df['bolsista'].str.title()
df['bolsista']

df['uf'] = df['uf'].str.upper()
df['uf']

df['cidade'] = df['cidade'].str.title()
df['cidade']

"""## 8. Criando novas colunas

### Exercício 16
Crie uma coluna chamada `media` com a média entre `nota1` e `nota2`.

### Exercício 17
Crie uma coluna chamada `aprovado`:
- `True` para média maior ou igual a **7**
- `False` caso contrário

### Exercício 18
Crie uma coluna chamada `situacao_faltas`:
- `Alto risco` para mais de 10 faltas
- `Atenção` para 6 a 10 faltas
- `Ok` para até 5 faltas

"""

df['media'] = (df['nota1'] + df['nota2']) / 2
df['media']

df['aprovado'] = df['media'] >= 7

df['faltas'] = pd.to_numeric(df['faltas'], errors='coerce')
df['situação_faltas'] = ''
df.loc[df['faltas'] <= 5, 'situação_faltas'] = 'OK'
df.loc[(df['faltas'] > 5) & (df['faltas'] <= 10), 'situação_faltas'] = 'Atenção'
df.loc[df['faltas'] > 10, 'situação_faltas'] = 'Alto risco'

"""## 9. Ordenação, contagem e agrupamento

### Exercício 19
Ordene os alunos pela coluna `media`, do maior para o menor.

### Exercício 20
Conte quantos alunos existem em cada curso.

### Exercício 21
Mostre a média de `nota1` por curso.

### Exercício 22
Mostre a média de faltas por turma.

"""

df.sort_values('media', ascending= False)

df.groupby('curso')['nome'].count()

df.groupby('curso')['nota1'].mean().round(1)

df.groupby('turma')['faltas'].mean()

"""## 10. Duplicatas e qualidade dos dados

### Exercício 23
Verifique se existem linhas duplicadas.

### Exercício 24
Remova as duplicatas e salve em um novo DataFrame chamado `df_limpo`.

### Exercício 25
Mostre os registros com emails possivelmente inválidos.
Dica: procure emails sem `@` ou sem `.com`.

"""

df.duplicated().sum()

df = df.drop_duplicates()

df.to_excel('df_limpo.xlsx', index = False)

"""## 11. Salvando um novo arquivo

### Exercício 26
Salve o DataFrame tratado em um novo arquivo Excel chamado:
`base_tratada_alunos.xlsx`

"""

df.to_excel('base_tratada_alunos.xlsx')

"""## 12. Introdução ao NumPy

### Exercício 27
Crie um array NumPy com os valores da coluna `nota1`, removendo os nulos.

### Exercício 28
Com esse array, calcule:
- média
- maior valor
- menor valor
- soma

### Exercício 29
Some **1 ponto** em todas as notas do array.

### Exercício 30
Mostre apenas as notas maiores que **7** usando NumPy.

"""

df['nota1']

import numpy as np
notas = np.array(df['nota1'].dropna())
media = notas.mean()
maior_valor = notas.max()
menor_valor = notas.min()
soma = notas.sum()
print(f'Média: {media}; maior valor: {maior_valor}; menor valor: {menor_valor}; soma: {soma:.2f}')

nota_mais = notas + 1

maior_sete = notas[notas >= 7]

"""## 13. Desafio final

### Exercício 31 — Desafio
Monte uma análise final respondendo:

1. Quantos alunos há em cada curso?
2. Qual curso tem a maior média de `nota1`?
3. Quantos alunos têm mais de 10 faltas?
4. Quantos alunos são bolsistas?
5. Há dados faltando? Em quais colunas?
6. Há duplicatas?
7. Gere um DataFrame final apenas com:
   - `nome`
   - `curso`
   - `media`
   - `aprovado`

Depois, ordene esse DataFrame pela `media` em ordem decrescente.

"""



"""## 14. Espaço para correção

Professor: aqui você pode ir resolvendo os exercícios em sala após os alunos tentarem.

"""

# Correção do professor