# -*- coding: utf-8 -*-
"""UC3_revisao_final_e_exercicios.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ad7YXIFGP8gy6g_DVp6Th0RZJ-XI_Je-

# UC3 — Revisão Final
## Funções Matemáticas e Probabilidade aplicadas à Inteligência Artificial

**Curso:** Técnico em Inteligência Artificial  
**Unidade Curricular:** UC3 — Aplicar funções de lógica matemática em Inteligência Artificial  
**Objetivo da aula:** revisar os principais conteúdos da UC3 e praticar com uma boa quantidade de exercícios, iniciando em sala e concluindo em casa.

---

## O que vamos revisar hoje

Nesta revisão, vamos retomar:

- funções lineares;
- funções polinomiais;
- funções exponenciais;
- funções logarítmicas;
- probabilidade básica;
- conexão desses conteúdos com Inteligência Artificial.

---

## Como usar este notebook

### Parte 1 — Revisão
Leia os resumos, observe os exemplos e relembre os conceitos principais.

### Parte 2 — Exercícios
Resolva os exercícios em ordem.  
Você pode começar em sala e terminar em casa.

### Parte 3 — Desafios opcionais
Para quem quiser ir além, há alguns desafios extras ao final.

# Parte 1 — Revisão dos conteúdos

## 1. Função Linear

### Forma geral

$$
f(x) = ax + b
$$

### Ideia principal
A função linear representa uma relação de crescimento ou decrescimento constante.

- `a` = taxa de variação
- `b` = valor inicial

### Exemplo
$$
f(x) = 2x + 3
$$

Se `x = 4`:

$$
f(4) = 2 \cdot 4 + 3 = 11
$$

### Onde isso aparece em IA?
- regressão linear;
- previsão de valores;
- interpretação de relação entre entrada e saída.
"""

'''
f(x) = x
f(x) = 2x
f(x) = 2x + 3
'''

def f_linear(x):
  return 2*x + 3

f_linear(4)

valores = [0, 1, 2, 3, 4]
for x in valores:
  print(f'f({x}) -> {f_linear(x)}')

"""**EXEMPLO PRÁTICO **

Vamos supor que uma corrida no aplicativo Uber é cobrado por um valor fixo de R5,00   e   mais R1,00 por KM rodados.
Construa uma função que represente a situação e calcula o valor de uma corrida de 15 KM.
"""

def uber(km):
  return 5 + 1*km

uber(15)

"""## 2. Função Polinomial

### Exemplo mais importante na UC3
Função do 2º grau:

$$
f(x) = ax^2 + bx + c
$$

### Ideia principal
A função polinomial permite representar comportamentos curvos.

### Exemplo
$$
f(x) = x^2 - 4x + 5
$$

### Observações
- se `a > 0`, a parábola abre para cima;
- se `a < 0`, a parábola abre para baixo.

### Onde isso aparece em IA?
- modelagem de relações não lineares;
- transformação de variáveis (`x²`, `x³`);
- regressão polinomial.
"""

# Exemplo de função polinomial
def f_polinomial(x):
  return x**2 - (4*x) + 5

valores = [0, 1, 2, 3, 4]
for x in valores:
  print(f'f({x}) -> {f_polinomial(x)}')

"""## 3. Função Exponencial

### Forma geral

$$
f(x) = a \cdot b^x
$$

### Ideia principal
Na função exponencial, o crescimento ou decrescimento acontece por multiplicação constante.

### Exemplo
$$
f(x) = 3 \cdot 2^x
$$

### Observações
- se `b > 1`, há crescimento;
- se `0 < b < 1`, há decrescimento.

### Onde isso aparece em IA?
- função sigmoid;
- probabilidades;
- crescimento de combinações;
- comportamento de certos algoritmos.
"""

# Exemplo de função exponencial
'''
f(x) = 2^x
f(1) = 2¹ = 2
f(2) = 2² = 4

f(x) = (-2)^x
f(1) = (-2)¹ = -2
f(2) = (-2)² = (-2)(-2)
f(3) = (-2)³ = (-2)(-2)(-2) = -8
'''

def f_exponencial(x):
  return 3*(2**x)

for x in valores:
  print(f'f({x}) -> {f_exponencial(x)}')

"""## 4. Função Logarítmica

### Forma geral

$$
f(x) = \log_b(x)
$$

### Ideia principal
O logaritmo responde: “a que potência a base deve ser elevada para obter esse valor?”

### Exemplo
$$
\log_2(8) = 3
$$

porque:

$$
2^3 = 8
$$

### Onde isso aparece em IA?
- entropia;
- funções de perda;
- análise de escalas;
- complexidade de algoritmos.
"""

# Exemplo de logaritmo
valor = [1, 2, 4, 8, 16]
import numpy as np
for x in valor:
  print(np.log2(x))

import math
#math.log(x, base)

for x in valor:
  print(math.log(x, 2))

"""## 5. Probabilidade Básica

### Fórmula

$$
P(A) = \frac{\text{casos favoráveis}}{\text{casos possíveis}}
$$

### Ideias principais
- probabilidade mede chance;
- eventos independentes: multiplicamos probabilidades;
- “e” é diferente de “ou”.

### Exemplos
- probabilidade de cara em uma moeda: \(1/2\)
- probabilidade de cara duas vezes seguidas: \((1/2) \cdot (1/2) = 1/4\)

### Onde isso aparece em IA?
- classificação;
- decisão baseada em probabilidades;
- Naive Bayes;
- previsão com incerteza.
"""

# Exemplo simples de decisão da IA com probabilidades

classes = ["A", "B", "C"]
probabilidades = [0.2, 0.2, 0.2]

maior_prob = probabilidades[0]
indice_maior = 0

for i in range(len(probabilidades)):
    if probabilidades[i] > maior_prob:
        maior_prob = probabilidades[i]
        indice_maior = i

decisao = classes[indice_maior]

print("Probabilidades:", probabilidades)
print("Decisão da IA:", decisao)

"""## 6. Resumo final da UC3

### O que você precisa saber

- Função linear → reta
- Função polinomial → curva
- Função exponencial → crescimento/decrescimento rápido
- Função logarítmica → crescimento lento, operação inversa da exponencial
- Probabilidade → mede chance e ajuda na tomada de decisão

### Conexão com IA

Toda a UC3 é base para temas futuros como:

- regressão linear;
- regressão polinomial;
- redes neurais;
- classificação;
- probabilidade em Machine Learning;
- entropia e teoria da informação.

# Parte 2 — Exercícios de revisão

## Bloco A — Função Linear

### Exercício 1
Considere a função:

$$
f(x) = 3x + 2
$$

Calcule:

- `f(0)`
- `f(1)`
- `f(4)`
"""

v1 = [0, 1, 4]

def f1(x):
  return 3*x + 2

for x in v1:
  print(f'f({x}) -> {f1(x)}')

"""### Exercício 2
Considere a função:

\[
g(x) = -2x + 5
\]

Calcule:

- `g(0)`
- `g(2)`
- `g(5)`
"""

valor = [0, 2, 5]

def ex_2(x):
  return -2*x + 5

for x in valor:
  print(f'f({x}) -> {ex_2(x)}')

"""### Exercício 3
Explique com suas palavras:

- o que representa o coeficiente `a`;
- o que representa o coeficiente `b`.
"""

'''
'a' representa a taxa de crescimento ou decrecimento
'b' o valor inicial
'''

"""### Exercício 4
Uma empresa cobra R\$ 10 por unidade consumida e ainda uma taxa fixa de R\$ 30.

1. Escreva a função que representa o custo total.
2. Calcule o custo para 5 unidades.
"""

def consumo(x):
  return 10*x + 30
uni = [5]

for x in uni:
  print(f'O valor gasto por 5 unidades é R${consumo(x)}')

"""## Bloco B — Função Polinomial

### Exercício 5
Considere a função:

$$
f(x) = x^2 + 2x + 1
$$

Calcule:

- `f(0)`
- `f(1)`
- `f(2)`
"""

def pol_5(x):
  return x**2 + (2*x) + 1

valor = [0, 1, 2]

for x in valor:
  print(f'f({x}) -> {pol_5(x)}')

"""### Exercício 6
Considere a função:

$$
g(x) = -x^2 + 4x + 1
$$

Responda:

1. A parábola abre para cima ou para baixo?
2. O gráfico tem ponto máximo ou mínimo?
"""

def pol_6(x):
  return -x**2 + (4*x) + 1

pol_6(1)

'''
1 - Abre para baixo.
2 - Tem ponto máximo.
'''

"""### Exercício 7
Explique a diferença entre:

- uma função linear;
- uma função polinomial do 2º grau.
"""

'''
Função linear são dois conjuntos de elementos que associa cada valor de entrada a uma saída, com uma raiz, no gráfico é representado por uma reta.
Já a função polinomial do 2° grau tem duas raizes e no gráfico é representado por uma parábula.

'''

"""### Exercício 8
Crie uma função polinomial simples que represente uma situação em que um valor cresce no início e depois diminui.
"""

#f(x) = x**2 + 1 + 5
import numpy as np
import matplotlib.pyplot as plt

t = np.linspace(0, 5, 200)
altura = -3*t**2 + 14*t + 3

plt.figure(figsize=(8, 5))
plt.plot(t, altura)

plt.axhline(0, color='black', linewidth=1)
plt.axvline(0, color='black', linewidth=1)

plt.title("Demanda")
plt.xlabel("meses")
plt.ylabel("máxima")
plt.grid()
plt.show()

"""## Bloco C — Função Exponencial

### Exercício 9
Considere a função:

$$
f(x) = 2 \cdot 3^x
$$

Calcule:

- `f(0)`
- `f(1)`
- `f(2)`
"""

def f(x):
  return 2* (3**x)

lados = [0, 1,  2]
[(x,f(x)) for x in lados]

"""### Exercício 10
Considere a função:

$$
g(x) = 100 \cdot (0.5)^x
$$

Responda:

1. Há crescimento ou decrescimento?
2. Quanto vale `g(1)`?
3. Quanto vale `g(3)`?
"""

def g(x):
  return 100 * (0.5**x)
valor = [1, 3]
[(x, g(x)) for x in valor]

for x in valor:
  print(f'g{x} =', g(x))

print('Há um decrécimento.')

"""### Exercício 11
Explique, com suas palavras, a diferença entre:

- crescimento linear;
- crescimento exponencial.
"""

'''
Crescimento linear aumento ou diminui de forma constante independeno do tempo.

Crescimetno exponencial cresce lentamente, depois dobra ou multiplica rapidamente com o tempo.
'''

"""### Exercício 12
Uma quantidade de dados dobra a cada ciclo e começa em 50.

1. Escreva a função.
2. Calcule os valores para `x = 0, 1, 2, 3`.
"""

def dobro(x):
  return 50 * (2**x)

valores = [0, 1, 2, 3]

[(x, dobro(x)) for x in valores]

"""## Bloco D — Função Logarítmica

### Exercício 13
Calcule:

- $$log_2(2)$$
- $$log_2(8)$$
- $$log_2(32)$$
"""

valores = [ 2, 8, 32]
[(x, np.log2(x)) for x in valores]

"""### Exercício 14
Explique por que:

$$
\log_2(16) = 4
$$
"""

'''
a base 2 está multiplicando ele mesmo a 4 para chegar ao valor de entrada.
'''

"""### Exercício 15
Explique a relação entre:

- função exponencial;
- função logarítmica.
"""

'''
Função exponencial é o crescimento constante do valor.
Enquanto a logaritima controla esse crescimento de forma lenta.

'''

"""### Exercício 16
Se você precisa representar 64 valores diferentes, quantos bits são necessários?
"""

print(f'São necessários {np.log2(64)} bits.')

"""## Bloco E — Probabilidade

### Exercício 17
Qual a probabilidade de sair número par em um dado?
"""

print('100% de 6 números possíveis')

"""### Exercício 18
Qual a probabilidade de sair cara duas vezes seguidas ao lançar uma moeda duas vezes?
"""

'''
c = 2/4
50%

'''

"""### Exercício 19
Ao lançar uma moeda e um dado, qual a probabilidade de sair:

1. cara e número 6  
2. cara ou número 6
"""

'''
p = 1/ 12 possibilidades
p = 7/12 possibilidades

'''

"""### Exercício 20
Explique a diferença entre:

- “cara e 6”
- “cara ou 6”
"""

'''
cara E 6  tem que acontecer os dois ao mesmo tempo.
cara OU 6 é a possibilidade de sair cara, 6 ou cara e 6.
'''

"""### Exercício 21
Uma IA retorna as seguintes probabilidades:

- Classe A: 0.2
- Classe B: 0.5
- Classe C: 0.3

Qual decisão a IA tomará? Explique.
"""

'''
Ela irá optar pela maior probabilidade

'''

"""### Exercício 22
Explique com suas palavras:

> “IA não toma decisões certas; IA toma decisões prováveis.”
"""

'''
Sua decisão é baseada em dados, optando pela maior chance dentre todas as probabilidades .

'''

"""## Bloco F — Integração com IA

### Exercício 23
Associe cada conteúdo a uma aplicação possível em IA:

- Função linear
- Função polinomial
- Função exponencial
- Função logarítmica
- Probabilidade
"""

'''
LINEAR - Ver as possibilidades de entrada e saída contínuos.
POLINÔMIO - Casos em que pode haver variáveis nos dados.
EXPONENCIAL - Crescimento e probabilidades de classisficação
LOGARÍTIMICA - Diminuir o tanho dos dados para melhor compreenssão de padrões.
PROBABILIDADE - Serve para previsão de eventos e patomada de decisões.
'''

"""### Exercício 24
Explique por que a UC3 é importante para quem vai estudar Machine Learning no futuro.
"""

'''
Nos ajuda compreender por que a IA tomou tal decisão, interpretando os dados do mais simples ao complexo. Para escolher qual modelo é melhor para
aquela finaliade, facilitando o aprendizado do algoritimo e avaliando se esse modelo é confiável.


'''

"""### Exercício 25
Dê um exemplo de situação em que uma IA poderia usar:

1. uma reta  
2. uma curva  
3. uma probabilidade
"""

'''
1 - Fazer uma estimativa de aumento de aluguel.
2 - Crescimento de uma populção
3 - Fazer reconhecimento facial

'''

"""# Parte 3 — Espaço para resolução"""

# Use este espaço para resolver os exercícios com Python, se desejar.

import numpy as np

"""# Parte 4 — Desafios opcionais

### Desafio 1
Crie uma função linear e uma função exponencial e compare os valores para `x = 0, 1, 2, 3, 4`.
"""

valores = [0, 1, 2, 3, 4]

def linear(x):
  return 2 * x + 1

def exp(x):
  return 2 ** x

for x in valores:
  print(f'x = {x}')
  print(f'linear = {linear(x)}')
  print(f'exponencial = {exp(x)}')

"""### Desafio 2
Crie um pequeno sistema que receba probabilidades de classes e escolha a decisão final da IA.

### Desafio 3
Monte uma tabela com 5 exemplos reais de onde cada conteúdo da UC3 aparece em Inteligência Artificial.

### Desafio 5
Pesquise e explique por que logaritmo aparece em entropia e em funções de perda no contexto de IA.

# Fechamento

Parabéns por concluir a UC3.

Se você entendeu os conceitos desta unidade, então já construiu uma base importante para os próximos assuntos do curso, especialmente:

- estatística;
- machine learning;
- redes neurais;
- análise de dados;
- classificação.

A UC3 não é “apenas matemática”.  
Ela é parte da base que sustenta a Inteligência Artificial.
"""